export enum AmazonDomainsEnum {
    AmazonEG = "https://www.amazon.eg/",
    AmazonBR = "https://www.amazon.com.br/",
    AmazonCA = "https://www.amazon.ca/",
    AmazonMX = "https://www.amazon.com.mx/",
    AmazonUS = "https://www.amazon.com/",
    AmazonCN = "https://www.amazon.cn/",
    AmazonIN = "https://www.amazon.in/",
    AmazonJP = "https://www.amazon.co.jp/",
    AmazonSA = "https://www.amazon.sa/",
    AmazonSG = "https://www.amazon.sg/",
    AmazonTR = "https://www.amazon.com.tr/",
    AmazonAE = "https://www.amazon.ae/",
    AmazonBE = "https://www.amazon.com.be/",
    AmazonFR = "https://www.amazon.fr/",
    AmazonDE = "https://www.amazon.de/",
    AmazonIT = "https://www.amazon.it/",
    AmazonNL = "https://www.amazon.nl/",
    AmazonPL = "https://www.amazon.pl/",
    AmazonES = "https://www.amazon.es/",
    AmazonSE = "https://www.amazon.se/",
    AmazonUK = "https://www.amazon.co.uk/",
    AmazonAU = "https://www.amazon.com.au/",
}
